using System.Security.Cryptography;
using System.Text;
using System.Text.RegularExpressions;

using Microsoft.EntityFrameworkCore;

using TitanMDM.Application.Helpdesk;
using TitanMDM.Domain.Entities;
using TitanMDM.Domain.Helpdesk;
using TitanMDM.Infrastructure.Persistence;

namespace TitanMDM.Infrastructure.Helpdesk;

public sealed record IncomingHelpdeskEmail(
    string Mailbox,
    string InternetMessageId,
    string? ConversationId,

    string FromEmail,
    string? FromName,

    IReadOnlyList<string> ToRecipients,
    IReadOnlyList<string> CcRecipients,
    IReadOnlyList<string> ReplyTo,

    string Subject,
    string Body,

    DateTime? ReceivedAtUtc,

    string? AutoSubmitted,
    string? Precedence);

public sealed class HelpdeskEmailImportService
{
    /*
     * Subject generated by TitanMDM:
     *
     * [TitanMDM][HD-XXXXXXXX-XXXXXX] Subject
     *
     * We deliberately require both TitanMDM and HD markers
     * to avoid associating arbitrary external subjects.
     */
    private static readonly Regex
        TicketNumberRegex =
            new(
                @"\[TitanMDM\]\[(HD-[A-Z0-9\-]+)\]",
                RegexOptions.IgnoreCase |
                RegexOptions.CultureInvariant |
                RegexOptions.Compiled);

    private readonly TitanMdmDbContext
        _db;

    private readonly IHelpdeskService
        _tickets;

    public HelpdeskEmailImportService(
        TitanMdmDbContext db,
        IHelpdeskService tickets)
    {
        _db =
            db;

        _tickets =
            tickets;
    }

    public async Task<Guid> ImportAsync(
     Guid organizationId,
     Guid mailboxActorUserId,
     IncomingHelpdeskEmail message,
     CancellationToken cancellationToken = default)
    {
        ValidateInput(
            organizationId,
            mailboxActorUserId,
            message);

        var mailbox =
            NormalizeEmail(
                message.Mailbox);

        var fromEmail =
            NormalizeEmail(
                message.FromEmail);

        var internetMessageId =
            message.InternetMessageId
                .Trim();

        var conversationId =
            string.IsNullOrWhiteSpace(
                message.ConversationId)
                    ? null
                    : message.ConversationId
                        .Trim();

        var messageKey =
            ComputeMessageKey(
                internetMessageId);

        var subject =
            NormalizeSubject(
                message.Subject);

        var body =
            NormalizeBody(
                message.Body);

        // ============================================================
        // FAST IDEMPOTENCY
        // ============================================================

        var alreadyImported =
            await FindImportedMessageAsync(
                organizationId,
                mailbox,
                messageKey,
                cancellationToken);

        if (alreadyImported is not null)
        {
            return alreadyImported
                .TicketId;
        }

        // ============================================================
        // MAILBOX ACTOR
        // ============================================================

        var mailboxActorExists =
            await _db.Users
                .AsNoTracking()
                .AnyAsync(
                    x =>
                        x.OrganizationId ==
                            organizationId
                        &&
                        x.Id ==
                            mailboxActorUserId
                        &&
                        x.IsActive,
                    cancellationToken);

        if (!mailboxActorExists)
        {
            throw new InvalidOperationException(
                "El usuario técnico del buzón no existe o está inactivo.");
        }

        // ============================================================
        // REQUESTER LOOKUP
        //
        // Puede no existir todavía como usuario TitanMDM.
        // En ese caso conservamos el actor técnico como UserId
        // interno y guardamos la identidad real del remitente
        // mediante SetEmailRequester / SetEmailAuthor.
        // ============================================================

        var requester =
            await _db.Users
                .AsNoTracking()
                .FirstOrDefaultAsync(
                    x =>
                        x.OrganizationId ==
                            organizationId
                        &&
                        x.Email ==
                            fromEmail
                        &&
                        x.IsActive,
                    cancellationToken);

        // ============================================================
        // SQL SERVER EXECUTION STRATEGY
        //
        // IMPORTANTE:
        //
        // TitanMDM tiene EnableRetryOnFailure habilitado.
        // Por tanto cualquier transacción explícita debe ejecutarse
        // dentro de Database.CreateExecutionStrategy().
        //
        // De lo contrario EF Core lanza:
        //
        // "The configured execution strategy
        //  'SqlServerRetryingExecutionStrategy'
        //  does not support user-initiated transactions."
        // ============================================================

        var executionStrategy =
            _db.Database
                .CreateExecutionStrategy();

        return await executionStrategy
            .ExecuteAsync(
                async () =>
                {
                    cancellationToken
                        .ThrowIfCancellationRequested();

                    await using var transaction =
                        await _db.Database
                            .BeginTransactionAsync(
                                cancellationToken);

                    try
                    {
                        // ====================================================
                        // SECOND IDEMPOTENCY CHECK
                        //
                        // Necesario porque dos workers/nodos pueden detectar
                        // el mismo mensaje antes de que alguno lo confirme.
                        // ====================================================

                        var existingInsideTransaction =
                            await FindImportedMessageAsync(
                                organizationId,
                                mailbox,
                                messageKey,
                                cancellationToken);

                        if (existingInsideTransaction is not null)
                        {
                            await transaction
                                .CommitAsync(
                                    cancellationToken);

                            return existingInsideTransaction
                                .TicketId;
                        }

                        // ====================================================
                        // THREAD RESOLUTION
                        //
                        // 1. Graph ConversationId
                        // 2. Marcador controlado [TitanMDM][HD-...]
                        // ====================================================

                        var ticket =
                            await ResolveExistingTicketAsync(
                                organizationId,
                                mailbox,
                                conversationId,
                                subject,
                                cancellationToken);

                        // ====================================================
                        // NEW TICKET
                        // ====================================================

                        if (ticket is null)
                        {
                            var created =
                                await _tickets
                                    .CreateTicketAsync(
                                        organizationId,
                                        mailboxActorUserId,
                                        new CreateHelpdeskTicketRequest(
                                            subject,
                                            body,
                                            "incident",
                                            "medium",
                                            "general",
                                            "email",
                                            null,
                                            requester?.Id
                                                ??
                                                mailboxActorUserId,
                                            null),
                                        cancellationToken);

                            ticket =
                                await _db.HelpdeskTickets
                                    .FirstAsync(
                                        x =>
                                            x.OrganizationId ==
                                                organizationId
                                            &&
                                            x.Id ==
                                                created.Id,
                                        cancellationToken);

                            ticket.SetEmailRequester(
                                message.FromName
                                    ??
                                    fromEmail,
                                fromEmail);

                            _db.HelpdeskTicketEvents
                                .Add(
                                    new HelpdeskTicketEvent(
                                        organizationId,
                                        ticket.Id,
                                        mailboxActorUserId,
                                        "email_received",
                                        $"Ticket creado desde correo de {fromEmail}."));
                        }
                        else
                        {
                            // ================================================
                            // EXISTING THREAD -> PUBLIC COMMENT
                            // ================================================

                            var comment =
                                new HelpdeskTicketComment(
                                    organizationId,
                                    ticket.Id,
                                    requester?.Id
                                        ??
                                        mailboxActorUserId,
                                    body,
                                    isInternal:
                                        false);

                            comment.SetEmailAuthor(
                                message.FromName
                                    ??
                                    fromEmail,
                                fromEmail);

                            _db.HelpdeskTicketComments
                                .Add(
                                    comment);

                            _db.HelpdeskTicketEvents
                                .Add(
                                    new HelpdeskTicketEvent(
                                        organizationId,
                                        ticket.Id,
                                        mailboxActorUserId,
                                        "email_reply",
                                        $"Respuesta por correo recibida de {fromEmail}."));

                            // ================================================
                            // CONTINUITY WORKFLOW
                            // ================================================

                            var previousStatus =
                                HelpdeskTicketStatus
                                    .Normalize(
                                        ticket.Status);

                            switch (previousStatus)
                            {
                                case HelpdeskTicketStatus.New:
                                    {
                                        ticket.Transition(
                                        HelpdeskTicketStatus.Open);

                                        AddStatusEvent(
                                        organizationId,
                                        ticket.Id,
                                        mailboxActorUserId,
                                        previousStatus,
                                        HelpdeskTicketStatus.Open);

                                        break;
                                    }

                                case HelpdeskTicketStatus.PendingUser:
                                    {
                                        var targetStatus =
                                        ticket.AssigneeUserId.HasValue
                                            ? HelpdeskTicketStatus.InProgress
                                            : HelpdeskTicketStatus.Open;

                                        ticket.Transition(
                                        targetStatus);

                                        AddStatusEvent(
                                        organizationId,
                                        ticket.Id,
                                        mailboxActorUserId,
                                        previousStatus,
                                        targetStatus);

                                        break;
                                    }

                                case HelpdeskTicketStatus.Resolved:
                                case HelpdeskTicketStatus.Closed:
                                    {
                                        ticket.Reopen();

                                        _db.HelpdeskTicketEvents
                                        .Add(
                                            new HelpdeskTicketEvent(
                                                organizationId,
                                                ticket.Id,
                                                mailboxActorUserId,
                                                "reopened_by_email",
                                                "Ticket reabierto automáticamente por una respuesta recibida por correo."));

                                        AddStatusEvent(
                                        organizationId,
                                        ticket.Id,
                                        mailboxActorUserId,
                                        previousStatus,
                                        HelpdeskTicketStatus.Open);

                                        break;
                                    }

                                case HelpdeskTicketStatus.Open:
                                case HelpdeskTicketStatus.InProgress:
                                    {
                                        break;
                                    }

                                default:
                                    {
                                        throw new InvalidOperationException(
                                        $"Estado de Helpdesk inesperado: '{ticket.Status}'.");
                                    }
                            }
                        }

                        // ====================================================
                        // EMAIL IDENTITY / IDEMPOTENCY
                        // ====================================================

                        _db.HelpdeskEmailMessages
                            .Add(
                                new HelpdeskEmailMessage(
                                    organizationId,
                                    ticket.Id,
                                    mailbox,
                                    internetMessageId,
                                    conversationId));

                        await _db.SaveChangesAsync(
                            cancellationToken);

                        await transaction
                            .CommitAsync(
                                cancellationToken);

                        return ticket.Id;
                    }
                    catch (DbUpdateException)
                    {
                        // ================================================
                        // IDEMPOTENCY / CONCURRENT IMPORT
                        //
                        // OrganizationId + Mailbox + MessageKey
                        // tiene índice UNIQUE.
                        // ================================================

                        try
                        {
                            await transaction
                                .RollbackAsync(
                                    CancellationToken.None);
                        }
                        catch
                        {
                            // No ocultar el error original.
                        }

                        _db.ChangeTracker
                            .Clear();

                        var winner =
                            await FindImportedMessageAsync(
                                organizationId,
                                mailbox,
                                messageKey,
                                cancellationToken);

                        if (winner is not null)
                        {
                            return winner
                                .TicketId;
                        }

                        throw;
                    }
                    catch
                    {
                        try
                        {
                            await transaction
                                .RollbackAsync(
                                    CancellationToken.None);
                        }
                        catch
                        {
                            // No ocultar el error original.
                        }

                        /*
                         * Si la estrategia decide reintentar una excepción
                         * transitoria, no debemos dejar entidades Added /
                         * Modified de un intento anterior en el ChangeTracker.
                         */
                        _db.ChangeTracker
                            .Clear();

                        throw;
                    }
                });
    }

    // ============================================================
    // THREAD RESOLUTION
    // ============================================================

    private async Task<HelpdeskTicket?>
        ResolveExistingTicketAsync(
            Guid organizationId,
            string mailbox,
            string? conversationId,
            string subject,
            CancellationToken cancellationToken)
    {
        /*
         * ========================================================
         * 1. GRAPH CONVERSATION ID
         * ========================================================
         */

        if (!string.IsNullOrWhiteSpace(
                conversationId))
        {
            var matchingTicketIds =
                await _db.HelpdeskEmailMessages
                    .AsNoTracking()
                    .Where(
                        x =>
                            x.OrganizationId ==
                                organizationId
                            &&
                            x.Mailbox ==
                                mailbox
                            &&
                            x.ConversationId ==
                                conversationId)
                    .Select(
                        x =>
                            x.TicketId)
                    .Distinct()
                    .Take(2)
                    .ToListAsync(
                        cancellationToken);

            if (matchingTicketIds.Count > 1)
            {
                throw new InvalidOperationException(
                    "Una conversación de correo está asociada a más de un ticket. " +
                    "Se requiere revisión administrativa.");
            }

            if (matchingTicketIds.Count == 1)
            {
                return await _db.HelpdeskTickets
                    .FirstOrDefaultAsync(
                        x =>
                            x.OrganizationId ==
                                organizationId
                            &&
                            x.Id ==
                                matchingTicketIds[0],
                        cancellationToken);
            }
        }

        /*
         * ========================================================
         * 2. TITANMDM SUBJECT MARKER
         * ========================================================
         *
         * Outbound mail is generated as:
         *
         * [TitanMDM][HD-...] Subject
         *
         * This gives us a controlled fallback if Microsoft creates
         * another ConversationId during forwarding/reply scenarios.
         */

        var ticketNumber =
            ExtractTicketNumber(
                subject);

        if (ticketNumber is null)
        {
            return null;
        }

        var ticketIds =
            await _db.HelpdeskTickets
                .AsNoTracking()
                .Where(
                    x =>
                        x.OrganizationId ==
                            organizationId
                        &&
                        x.Number ==
                            ticketNumber)
                .Select(
                    x =>
                        x.Id)
                .Take(2)
                .ToListAsync(
                    cancellationToken);

        if (ticketIds.Count > 1)
        {
            throw new InvalidOperationException(
                $"El número de ticket '{ticketNumber}' no es único.");
        }

        if (ticketIds.Count == 0)
        {
            return null;
        }

        return await _db.HelpdeskTickets
            .FirstOrDefaultAsync(
                x =>
                    x.OrganizationId ==
                        organizationId
                    &&
                    x.Id ==
                        ticketIds[0],
                cancellationToken);
    }

    // ============================================================
    // IDEMPOTENCY LOOKUP
    // ============================================================

    private async Task<HelpdeskEmailMessage?>
        FindImportedMessageAsync(
            Guid organizationId,
            string mailbox,
            string messageKey,
            CancellationToken cancellationToken)
    {
        return await _db.HelpdeskEmailMessages
            .AsNoTracking()
            .FirstOrDefaultAsync(
                x =>
                    x.OrganizationId ==
                        organizationId
                    &&
                    x.Mailbox ==
                        mailbox
                    &&
                    x.MessageKey ==
                        messageKey,
                cancellationToken);
    }

    // ============================================================
    // STATUS AUDIT
    // ============================================================

    private void AddStatusEvent(
        Guid organizationId,
        Guid ticketId,
        Guid actorUserId,
        string previousStatus,
        string newStatus)
    {
        if (string.Equals(
                previousStatus,
                newStatus,
                StringComparison.OrdinalIgnoreCase))
        {
            return;
        }

        _db.HelpdeskTicketEvents
            .Add(
                new HelpdeskTicketEvent(
                    organizationId,
                    ticketId,
                    actorUserId,
                    "status",
                    $"Estado actualizado de {previousStatus} a {newStatus} después de recibir correo del solicitante."));
    }

    // ============================================================
    // VALIDATION
    // ============================================================

    private static void ValidateInput(
        Guid organizationId,
        Guid mailboxActorUserId,
        IncomingHelpdeskEmail message)
    {
        if (organizationId == Guid.Empty)
        {
            throw new ArgumentException(
                "OrganizationId is required.",
                nameof(organizationId));
        }

        if (mailboxActorUserId == Guid.Empty)
        {
            throw new ArgumentException(
                "Mailbox actor user is required.",
                nameof(mailboxActorUserId));
        }

        ArgumentNullException
            .ThrowIfNull(
                message);

        if (string.IsNullOrWhiteSpace(
                message.InternetMessageId)
            ||
            message.InternetMessageId
                .Trim()
                .Length >
                998)
        {
            throw new ArgumentException(
                "InternetMessageId inválido.",
                nameof(message));
        }

        if (string.IsNullOrWhiteSpace(
                message.FromEmail)
            ||
            message.FromEmail
                .Trim()
                .Length >
                320)
        {
            throw new ArgumentException(
                "Correo del remitente inválido.",
                nameof(message));
        }

        if (string.IsNullOrWhiteSpace(
                message.Mailbox)
            ||
            message.Mailbox
                .Trim()
                .Length >
                320)
        {
            throw new ArgumentException(
                "Buzón Helpdesk inválido.",
                nameof(message));
        }

        if (message.ConversationId?
                .Trim()
                .Length >
            512)
        {
            throw new ArgumentException(
                "ConversationId inválido.",
                nameof(message));
        }
    }

    // ============================================================
    // NORMALIZATION
    // ============================================================

    private static string NormalizeEmail(
        string value)
    {
        return value
            .Trim()
            .ToLowerInvariant();
    }

    private static string NormalizeSubject(
        string? value)
    {
        var subject =
            string.IsNullOrWhiteSpace(
                value)
                ? "Solicitud recibida por correo"
                : value.Trim();

        return subject[
            ..Math.Min(
                subject.Length,
                250)];
    }

    private static string NormalizeBody(
        string? value)
    {
        var body =
            string.IsNullOrWhiteSpace(
                value)
                ? "Mensaje sin contenido de texto."
                : value.Trim();

        return body[
            ..Math.Min(
                body.Length,
                4000)];
    }

    // ============================================================
    // TICKET NUMBER
    // ============================================================

    private static string?
        ExtractTicketNumber(
            string? subject)
    {
        if (string.IsNullOrWhiteSpace(
                subject))
        {
            return null;
        }

        var match =
            TicketNumberRegex
                .Match(
                    subject);

        if (!match.Success ||
            match.Groups.Count <
                2)
        {
            return null;
        }

        var value =
            match.Groups[1]
                .Value
                .Trim()
                .ToUpperInvariant();

        return value.Length
            is > 0
            and <= 32
                ? value
                : null;
    }

    // ============================================================
    // MESSAGE KEY
    // ============================================================

    private static string ComputeMessageKey(
        string internetMessageId)
    {
        return Convert
            .ToHexString(
                SHA256.HashData(
                    Encoding.UTF8
                        .GetBytes(
                            internetMessageId)));
    }
}